---
title: *Cepaea* polymorphism and parasites
author: "Armelle Ansart, Claudia Gérard, Marine Proux, Maxime Dahirel (this code by M. Dahirel)"
date:
output: 
  html_document:
    theme: yeti
    toc: TRUE
    toc_float: TRUE
editor_options:
  chunk_output_type: console
bibliography:
csl:
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE, message = FALSE)
```


# A brief introduction

<!--to do-->

# Part 1 : Preparation

## 1A - packages

```{r packages-loading}
#library(rstan) ## Stan backend
library(cmdstanr) ## Stan backend (another)
library(brms) ## the interface we are using

library(tidyverse)
library(bayesplot)
library(tidybayes)
library(matrixStats)

library(QGglmm) ## this package is needed to help convert variance-covariance matrices from latent to data scale

library(patchwork) #plotting

library(here)

## some useful default settings
#rstan_options(auto_write = TRUE) #for rstan
options(mc.cores = 4) ## reduce/increase depending on cores available
N_chains <- 4
N_warmup <- 2000 
N_iter <- N_warmup + 2000 
```


## 1B – data loading and wrangling

```{r data-load}
raw_behaviour <- read_csv(here("data","cepaea_2019_behaviour.csv"))
raw_parasite <- read_csv(here("data","cepaea_2019_parasite.csv"))
```


```{r data-prep}
#### don't forget removing the dead one when relevant
data_parasite<-raw_parasite %>% 
  mutate(Nematode_live_all = data_parasite %>% 
           select(c(Nematode_0_1_free, Nematode_1_3_free, 
                    Nematode_3_5_free, Nematode_5_plus_free, 
                    Nematode_1_3_lung, Nematode_3_5_lung, 
                    Nematode_5_plus_lung)) %>% 
           rowSums()) %>% 
  mutate(Nematode_encaps_all = Nematode_white_encaps + Nematode_dark_encaps)



data <- left_join(raw_behaviour,data_parasite) %>% 
  filter(dead==0) %>% 
  #remove the dead individual from the dataset 
  #!!THIS IS THE ONE WITH THE MOST NEMATODES BY FAR (102), this is natural history info to not forget
  #we then standardize covariates
  mutate(is.shaded = as.numeric(population=="shaded")-mean(as.numeric(population=="is.shaded")),
         scale_size = scale(shell_diameter)[,1])
```


```{r data-prep-mvt}
#we then define our movement variable
data_test <- data %>% 
  mutate(has.moved = FPT1 < 1200) %>% 
  mutate(mvt = (1/(FPT3-FPT1))) %>% 
  #mutate(mvt = replace(mvt,which(has.moved == FALSE),0)) %>% 
  #mutate(mvt = scale(mvt)[,1])  ##first approx, include inactive in estimates of scaling
## individuals with fpt1>=1200 are NOT active, so should not count towards mvt model
## is time to activity itself actually a relevant variable? NO (not stdised in the petri to, table phase, just let them habituate until they move)
```

See the model tests script for why we choose these transformations for movement and food intake data

# model 

```{r}
bf_trema<-bf(Trematode_kidney|subset(session==1) ~ is.shaded * ( band_number + fusion) + scale_size + (1|series)+(1|q|fullID),family=poisson)
bf_nemaL<-bf(Nematode_live_all|subset(session==1 & population=="sun_exposed") ~ band_number + fusion + scale_size + (1|series)+(1|q|fullID),family=poisson)
bf_food<-bf(food ~  is.shaded * (band_number + fusion) + scale_size + (1|series)+(1|q|fullID))
bf_mvt<-bf(mvt|subset(FPT1 < 1200) + cens(-1*(FPT3>=1200)) ~  is.shaded * (band_number + fusion) + scale_size + (1|series)+(1|q|fullID))

##group column is actually just lettercode, worth renaming removing?
## true grouping variable is series, snails boxed by band*landscape, 10 of each taken in series, then replaced in box before second test

mod<-brm(mvbf(bf_food+bf_trema+bf_nemaL+bf_mvt),
           data=data,
        chains=4,iter=2000,warmup=1000,
        prior=c(set_prior("normal(0,1)",class="Intercept",resp=c("Trematodekidney","Nematodeliveall")),
                set_prior("normal(0,1)",class="Intercept",resp=c("food","mvt")),
                set_prior("normal(0,1)",class="b",resp=c("Trematodekidney","Nematodeliveall","food","mvt")),
                set_prior("normal(0,1)", class="sd",resp=c("Trematodekidney","Nematodeliveall","food","mvt")),
                #set_prior("constant(0.01)",class="sigma",resp="scalesize"),
                set_prior("normal(0,1)",class="sigma",resp=c("mvt","food")),
                set_prior("lkj(2)",class="cor")),
        backend="cmdstanr",seed=42,control=list(adapt_delta=0.99,max_treedepth=10))

## what about rescor between food and mvt if gaussian
## two reasons not possible: for rescor, all traits need to be gaussian in the multivar model
## if i do a sep model with just food and mvt, error because rescor doesn't allow for cens or subset aterms (only se mi and weights)

### for enkysted nematodes: cannot analyse total N because probably accrue with age, which we do not know here
### compare proportion of in black versus in white would probs need to know actual surface of each (+ bias towards trapping close to opening, where more black), so just natural history and evidence that nematodes are present in marais, just not when we sampled (seasonality?)

data_para$is.shaded = as.numeric(data_para$population=="shaded")-mean(as.numeric(data_para$population=="is.shaded"))
data_para$scale_size = scale(data_para$shell_diameter)[,1]

mod_history<-brm(Nematode_encaps_all>0 ~ is.shaded * ( band_number + fusion ) + scale_size,family=bernoulli,
         data=data_para, chains=4, iter=2000, warmup=1000,
         prior=c(set_prior("normal(0,1.5)",class="Intercept"),
                 set_prior("normal(0,1)",class="b")),
         backend="cmdstanr",seed=42)

# ideally would include size as a correlated response in the multivar, not a covariate, but splitting indvar bw sigma and SD is WAY TOO HARD
mod_size <-brm(bf(scale_size|subset(session==1) ~ is.shaded * ( band_number + fusion )),
         data=data, chains=4, iter=2000, warmup=1000,
         prior=c(
           set_prior("normal(0,1)",class="Intercept"),
           set_prior("normal(0,1)",class="b"),
           set_prior("normal(0,1)",class="sigma")),
         backend="cmdstanr",seed=42,control=list(max_treedepth=20))


#5band smaller in shaded but not sunshaded
#if correct result, possible interpretations
# actually smaller adult, early maturity (but why 5 only)
# small adult 5 survive more in shaded
# revisit old data from eric to confirm??

## pattern same in old cornu data (arcaisCornupheno in phd folder) intermediate vs ferme, ouvert is vineyard (no cepaea there), so something cross specific and cross temp
```

```{r}
data %>% 
  select(population,band_number, is.shaded) %>% 
  distinct() %>% 
  mutate(scale_size=0, session=1, FPT1=0,fusion="no") %>% 
  add_fitted_draws(mod,re_formula=NA,resp="mvt") %>% 
  ggplot() +
  stat_eye(aes(band_number,.value,fill=population),position="dodge",slab_alpha=0.7)+
  coord_cartesian(ylim=c(-2,4))


ggplot() +
  geom_line(data=subset(data,FPT1<1200),aes(x = as.numeric(factor(band_number))+0.25*session-0.5-0.4*is.shaded,col=population, y=mvt, group=fullID), show.legend = FALSE,alpha=0.4) +
  geom_point(data=subset(data,FPT1<1200),aes(x = as.numeric(factor(band_number))+0.25*session-0.5-0.4*is.shaded,col=population, y=mvt), show.legend = FALSE,alpha=0.4)+
  coord_cartesian(ylim=c(-2,4))
```

```{r}
data %>% 
  select(band_number, is.shaded) %>% 
  distinct() %>% 
  mutate(scale_size=0, session=1, FPT1=0,fusion="no", population="sun_exposed") %>% 
  add_fitted_draws(mod,re_formula=NA,resp="Nematodeliveall") %>%  ## but re_formula NA not right for poisson ORLE, right? at least not for mean
  ungroup() %>% 
  ggplot() +
  stat_eye(aes(band_number,.value),slab_alpha=0.7)+
  geom_point(data=data %>% filter(session==1),aes(band_number,Nematode_live_all),alpha=0.5,position=position_jitter(height=0))
```

```{r}
data %>% 
  select(band_number, is.shaded,population) %>% 
  distinct() %>% 
  mutate(session=1, FPT1=0,fusion="no") %>%
  expand_grid(scale_size=c(-30:30)/10) %>% 
  add_fitted_draws(mod,re_formula=NA,resp="food") %>%  ## but re_formula NA not right for poisson ORLE, right? at least not for mean
  ungroup() %>% 
  ggplot() +
  stat_lineribbon(aes(scale_size,.value,fill=population),.width=c(0.01,0.95))+
  geom_point(data=data,aes(scale_size, food,col=population),alpha=0.5)+
  facet_wrap(~population)
```

+ figure trematode to do + individual level correlation grid

